crab report -d crab_projects/crab_SkimDsPhiPi_2024eraF_stream0_Mini_v3
crab report -d crab_projects/crab_SkimDsPhiPi_2024eraF_stream1_Mini_v3
crab report -d crab_projects/crab_SkimDsPhiPi_2024eraF_stream2_Mini_v3
crab report -d crab_projects/crab_SkimDsPhiPi_2024eraF_stream3_Mini_v3
crab report -d crab_projects/crab_SkimDsPhiPi_2024eraF_stream4_Mini_v3
crab report -d crab_projects/crab_SkimDsPhiPi_2024eraF_stream5_Mini_v3
crab report -d crab_projects/crab_SkimDsPhiPi_2024eraF_stream6_Mini_v3
crab report -d crab_projects/crab_SkimDsPhiPi_2024eraF_stream7_Mini_v3
