crab status -d crab_projects/crab_SkimTau3mu_2023eraB_stream0_Mini_v3
crab status -d crab_projects/crab_SkimTau3mu_2023eraB_stream1_Mini_v3
crab status -d crab_projects/crab_SkimTau3mu_2023eraB_stream2_Mini_v3
crab status -d crab_projects/crab_SkimTau3mu_2023eraB_stream3_Mini_v3
crab status -d crab_projects/crab_SkimTau3mu_2023eraB_stream4_Mini_v3
crab status -d crab_projects/crab_SkimTau3mu_2023eraB_stream5_Mini_v3
crab status -d crab_projects/crab_SkimTau3mu_2023eraB_stream6_Mini_v3
crab status -d crab_projects/crab_SkimTau3mu_2023eraB_stream7_Mini_v3
