#!/bin/bash
chmod 777 -R *
cd 2024F_3_control_230924
echo condor_submit my_HTCondor_data_control_2024F_3_control_0.job -name ettore
condor_submit my_HTCondor_data_control_2024F_3_control_0.job -name ettore
echo condor_submit my_HTCondor_data_control_2024F_3_control_1.job -name ettore
condor_submit my_HTCondor_data_control_2024F_3_control_1.job -name ettore
echo condor_submit my_HTCondor_data_control_2024F_3_control_2.job -name ettore
condor_submit my_HTCondor_data_control_2024F_3_control_2.job -name ettore
echo condor_submit my_HTCondor_data_control_2024F_3_control_3.job -name ettore
condor_submit my_HTCondor_data_control_2024F_3_control_3.job -name ettore
echo condor_submit my_HTCondor_data_control_2024F_3_control_4.job -name ettore
condor_submit my_HTCondor_data_control_2024F_3_control_4.job -name ettore
echo condor_submit my_HTCondor_data_control_2024F_3_control_5.job -name ettore
condor_submit my_HTCondor_data_control_2024F_3_control_5.job -name ettore
echo condor_submit my_HTCondor_data_control_2024F_3_control_6.job -name ettore
condor_submit my_HTCondor_data_control_2024F_3_control_6.job -name ettore
echo condor_submit my_HTCondor_data_control_2024F_3_control_7.job -name ettore
condor_submit my_HTCondor_data_control_2024F_3_control_7.job -name ettore
