#!/bin/bash
chmod 777 -R *
cd Run4_MinBias_tau3mu_Run4_minBias021224
echo condor_submit my_HTCondor_MC_Run4_MinBiasRun4_MinBias_tau3mu_0.job -name ettore
condor_submit my_HTCondor_MC_Run4_MinBiasRun4_MinBias_tau3mu_0.job -name ettore
echo condor_submit my_HTCondor_MC_Run4_MinBiasRun4_MinBias_tau3mu_1.job -name ettore
condor_submit my_HTCondor_MC_Run4_MinBiasRun4_MinBias_tau3mu_1.job -name ettore
echo condor_submit my_HTCondor_MC_Run4_MinBiasRun4_MinBias_tau3mu_2.job -name ettore
condor_submit my_HTCondor_MC_Run4_MinBiasRun4_MinBias_tau3mu_2.job -name ettore
echo condor_submit my_HTCondor_MC_Run4_MinBiasRun4_MinBias_tau3mu_3.job -name ettore
condor_submit my_HTCondor_MC_Run4_MinBiasRun4_MinBias_tau3mu_3.job -name ettore
echo condor_submit my_HTCondor_MC_Run4_MinBiasRun4_MinBias_tau3mu_4.job -name ettore
condor_submit my_HTCondor_MC_Run4_MinBiasRun4_MinBias_tau3mu_4.job -name ettore
echo condor_submit my_HTCondor_MC_Run4_MinBiasRun4_MinBias_tau3mu_5.job -name ettore
condor_submit my_HTCondor_MC_Run4_MinBiasRun4_MinBias_tau3mu_5.job -name ettore
echo condor_submit my_HTCondor_MC_Run4_MinBiasRun4_MinBias_tau3mu_6.job -name ettore
condor_submit my_HTCondor_MC_Run4_MinBiasRun4_MinBias_tau3mu_6.job -name ettore
echo condor_submit my_HTCondor_MC_Run4_MinBiasRun4_MinBias_tau3mu_7.job -name ettore
condor_submit my_HTCondor_MC_Run4_MinBiasRun4_MinBias_tau3mu_7.job -name ettore
echo condor_submit my_HTCondor_MC_Run4_MinBiasRun4_MinBias_tau3mu_8.job -name ettore
condor_submit my_HTCondor_MC_Run4_MinBiasRun4_MinBias_tau3mu_8.job -name ettore
echo condor_submit my_HTCondor_MC_Run4_MinBiasRun4_MinBias_tau3mu_9.job -name ettore
condor_submit my_HTCondor_MC_Run4_MinBiasRun4_MinBias_tau3mu_9.job -name ettore
echo condor_submit my_HTCondor_MC_Run4_MinBiasRun4_MinBias_tau3mu_10.job -name ettore
condor_submit my_HTCondor_MC_Run4_MinBiasRun4_MinBias_tau3mu_10.job -name ettore
echo condor_submit my_HTCondor_MC_Run4_MinBiasRun4_MinBias_tau3mu_11.job -name ettore
condor_submit my_HTCondor_MC_Run4_MinBiasRun4_MinBias_tau3mu_11.job -name ettore
echo condor_submit my_HTCondor_MC_Run4_MinBiasRun4_MinBias_tau3mu_12.job -name ettore
condor_submit my_HTCondor_MC_Run4_MinBiasRun4_MinBias_tau3mu_12.job -name ettore
echo condor_submit my_HTCondor_MC_Run4_MinBiasRun4_MinBias_tau3mu_13.job -name ettore
condor_submit my_HTCondor_MC_Run4_MinBiasRun4_MinBias_tau3mu_13.job -name ettore
echo condor_submit my_HTCondor_MC_Run4_MinBiasRun4_MinBias_tau3mu_14.job -name ettore
condor_submit my_HTCondor_MC_Run4_MinBiasRun4_MinBias_tau3mu_14.job -name ettore
echo condor_submit my_HTCondor_MC_Run4_MinBiasRun4_MinBias_tau3mu_15.job -name ettore
condor_submit my_HTCondor_MC_Run4_MinBiasRun4_MinBias_tau3mu_15.job -name ettore
echo condor_submit my_HTCondor_MC_Run4_MinBiasRun4_MinBias_tau3mu_16.job -name ettore
condor_submit my_HTCondor_MC_Run4_MinBiasRun4_MinBias_tau3mu_16.job -name ettore
echo condor_submit my_HTCondor_MC_Run4_MinBiasRun4_MinBias_tau3mu_17.job -name ettore
condor_submit my_HTCondor_MC_Run4_MinBiasRun4_MinBias_tau3mu_17.job -name ettore
echo condor_submit my_HTCondor_MC_Run4_MinBiasRun4_MinBias_tau3mu_18.job -name ettore
condor_submit my_HTCondor_MC_Run4_MinBiasRun4_MinBias_tau3mu_18.job -name ettore
echo condor_submit my_HTCondor_MC_Run4_MinBiasRun4_MinBias_tau3mu_19.job -name ettore
condor_submit my_HTCondor_MC_Run4_MinBiasRun4_MinBias_tau3mu_19.job -name ettore
echo condor_submit my_HTCondor_MC_Run4_MinBiasRun4_MinBias_tau3mu_20.job -name ettore
condor_submit my_HTCondor_MC_Run4_MinBiasRun4_MinBias_tau3mu_20.job -name ettore
echo condor_submit my_HTCondor_MC_Run4_MinBiasRun4_MinBias_tau3mu_21.job -name ettore
condor_submit my_HTCondor_MC_Run4_MinBiasRun4_MinBias_tau3mu_21.job -name ettore
echo condor_submit my_HTCondor_MC_Run4_MinBiasRun4_MinBias_tau3mu_22.job -name ettore
condor_submit my_HTCondor_MC_Run4_MinBiasRun4_MinBias_tau3mu_22.job -name ettore
echo condor_submit my_HTCondor_MC_Run4_MinBiasRun4_MinBias_tau3mu_23.job -name ettore
condor_submit my_HTCondor_MC_Run4_MinBiasRun4_MinBias_tau3mu_23.job -name ettore
echo condor_submit my_HTCondor_MC_Run4_MinBiasRun4_MinBias_tau3mu_24.job -name ettore
condor_submit my_HTCondor_MC_Run4_MinBiasRun4_MinBias_tau3mu_24.job -name ettore
