crab status -d crab_projects/crab_SkimDsPhiPi_2024eraG_stream0_Mini_v3
crab status -d crab_projects/crab_SkimDsPhiPi_2024eraG_stream1_Mini_v3
crab status -d crab_projects/crab_SkimDsPhiPi_2024eraG_stream2_Mini_v3
crab status -d crab_projects/crab_SkimDsPhiPi_2024eraG_stream3_Mini_v3
crab status -d crab_projects/crab_SkimDsPhiPi_2024eraG_stream4_Mini_v3
crab status -d crab_projects/crab_SkimDsPhiPi_2024eraG_stream5_Mini_v3
crab status -d crab_projects/crab_SkimDsPhiPi_2024eraG_stream6_Mini_v3
crab status -d crab_projects/crab_SkimDsPhiPi_2024eraG_stream7_Mini_v3
